project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "XinXin Li"
  site-url: https://XinxinLi.github.io
  favicon: images/site-logo.png
  repo-url: https://github.com/XinxinLi2004/XinxinLi.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    left: |
      [XinxinLi](https://XinxinLi.github.io)<br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
   #   - text: "Publications"
     #   href: publications.qmd
    #  - text: "Books"
    #    href: books.qmd
     # - text: "Blogs"
    #    href: blog.qmd
    #  - text: "Codes"
     #   href: codes.qmd
      #- text: "Experience"
      #  href: about.qmd
      - text: "CV"
        href: XINXIN_LI_CV.pdf
      - text: "Transcript"
        href: Transcript.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细